"""Init

Revision ID: 19ddbb32a70a
Revises:
Create Date: 2024-12-04 11:44:01.307168

"""

from typing import Sequence, Union

from alembic import op  # noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19ddbb32a70a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("DEPOSIT", "WITHDRAW", name="transactiontypes"),
            nullable=False,
        ),
        sa.Column("transaction_amount", sa.Float(), nullable=False),
        sa.Column("second_received", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("second_received"),
    )
    op.create_index(
        op.f("ix_transactions_transaction_id"),
        "transactions",
        ["transaction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_transaction_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("users")
    # ### end Alembic commands ###
